### ISSUE TITLE
netcat -q 0

### ISSUE THREAD

**Issue by calebeby** [ruyadorno/prettierme#1]
Hello,

For me, this script only works if I use `nc -q 0 127.0.0.1 ...` rather than `nc 127.0.0.1 ...`. If I use this script without the `-q 0` flag, it waits and does nothing until I `^C`. My understanding is that the `-q 0` flag causes the connection to end right away, rather than waiting for the server to close it. I am running arch linux, and have tried both `bsd-netcat` and `gnu-netcat`. The same issue applies to `eslintme`

**Comment by josephfrazier** [comment]
Hey @calebeby, `prettier_d` author here. `prettier_d` actually comes with a `prettier_dnc` script that handles this for you (I encountered the same issue and fixed it there). If you install `prettier_d` globally and then run `prettier_d start`, you can use it like `prettier_dnc < ./path/to/file.js`.

The source code also shows how `prettierme` could determine whether to use `-q 0`: https://github.com/josephfrazier/prettier_d/blob/6e5689bc04b10b38243ee4975cdb742b49d07f98/bin/prettier_dnc.sh

**Comment by calebeby** [comment]
OK, I'll stick to using pretttier_dnc for now. I'll leave this issue open in case @ruyadorno wants to implement this. Thanks

**Comment by ruyadorno** [comment]
@calebeby thanks for reporting! 😊 

@josephfrazier that seems like a smart and easy fix, I'll bring it over to `prettierme` too, thanks so much for letting me know! 🏆

**Comment by ruyadorno** [comment]
landed on [v3.0.0](https://github.com/ruyadorno/prettierme/releases/tag/v3.0.0)
