### ISSUE TITLE
Support XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by barrettruth** [ruyadorno/prettierme#6]
If XDG_RUNTIME_DIR is set, prettierd respects it and places the .prettierd file there.

Prettierme should as well, especially as all that is needed is to convert all lines with
`~/.prettierd` to `${XDG_RUNTIME_DIR:-$HOME}/.prettierd}`

**Comment by barrett-ruth** [comment]
Nevermind, realized that the prettierd file is the data file for the daemon and not the configuration file. Would still be nice to support some XDG base specification though, but that likely rests on prettierd and not prettierme.
